server:
  port: 8888

# 配置日志
logging:
  #path: ~/Code/springboot/log
  # 日志格式
  pattern:
    console: "%d - %msg%n"
  # 日志级别
  level:
    com.zehua.zsl: debug
    org.springfromework.web: info
    org.hibernate: error
  # 日志路径和名称
  file:
    log/myspringboot.log